using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace MyArchitecture.Editor
{
    internal static class ArchitectureGeneratedSourceRecovery
    {
        private const string ApplicationReadOnlyOutputPath =
            "Assets/Generated/MyArchitecture/ReadOnlyModels.g.cs";
        private const string PackageReadOnlyOutputPath =
            "Packages/com.seikasan.myarchitecture/Runtime/Generated/Package/ReadOnlyPackageModels.g.cs";
        private const string ApplicationRegistrationOutputPath =
            "Assets/Generated/MyArchitecture/ArchitectureAutoRegistration.g.cs";
        private const string PackageRegistrationOutputPath =
            "Packages/com.seikasan.myarchitecture/Runtime/Generated/Package/ArchitecturePackageAutoRegistration.g.cs";
        private const string FrameworkRootPath = "Packages/com.seikasan.myarchitecture/";

        private static bool _isGenerating;

        static ArchitectureGeneratedSourceRecovery()
        {
            CompilationPipeline.compilationStarted += _ => Generate();
        }

        [MenuItem("Tools/MyArchitecture/Generate/Recover Generated Files From Sources")]
        public static void Generate()
        {
            if (_isGenerating)
            {
                return;
            }

            _isGenerating = true;

            try
            {
                var types = SourceScanner.Scan().ToArray();

                bool changed = false;
                changed |= WriteIfChanged(
                    ApplicationReadOnlyOutputPath,
                    BuildReadOnlySource(types, path => !IsFrameworkOwnedPath(path)));
                changed |= WriteIfChanged(
                    PackageReadOnlyOutputPath,
                    BuildReadOnlySource(types, IsFrameworkOwnedPath));
                changed |= WriteIfChanged(
                    ApplicationRegistrationOutputPath,
                    BuildRegistrationSource(
                        "ArchitectureAutoRegistration",
                        types,
                        path => !IsFrameworkOwnedPath(path)));
                changed |= WriteIfChanged(
                    PackageRegistrationOutputPath,
                    BuildRegistrationSource(
                        "ArchitecturePackageAutoRegistration",
                        types,
                        IsFrameworkOwnedPath));

                if (changed)
                {
                    Debug.Log("MyArchitecture generated files were refreshed from source before compilation.");
                }
            }
            catch (Exception exception)
            {
                Debug.LogWarning("MyArchitecture generated-file recovery failed. " + exception.Message);
            }
            finally
            {
                _isGenerating = false;
            }
        }

        private static string BuildReadOnlySource(
            IEnumerable<SourceType> types,
            Func<string, bool> pathFilter)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// This file is generated by ArchitectureGeneratedSourceRecovery.");

            foreach (var type in types
                         .Where(type => type.IsPartialModel)
                         .Where(type => pathFilter(type.Path))
                         .OrderBy(type => type.FullName))
            {
                AppendReadOnlyModel(builder, type);
            }

            return builder.ToString();
        }

        private static void AppendReadOnlyModel(StringBuilder builder, SourceType type)
        {
            var members = type.GetReadOnlyMembers()
                .OrderBy(member => member.Name)
                .ToArray();
            var hasNamespace = !string.IsNullOrEmpty(type.Namespace);
            var indent = hasNamespace ? "    " : string.Empty;
            var accessibility = type.IsPublic ? "public" : "internal";
            var interfaceName = "IReadOnly" + type.Name;

            builder.AppendLine();

            if (hasNamespace)
            {
                builder.Append("namespace ").AppendLine(type.Namespace);
                builder.AppendLine("{");
            }

            foreach (var usingDirective in type.UsingDirectives)
            {
                builder.Append(indent).AppendLine(usingDirective);
            }

            if (type.UsingDirectives.Count > 0)
            {
                builder.AppendLine();
            }

            builder.Append(indent)
                .Append(accessibility)
                .Append(" interface ")
                .Append(interfaceName)
                .Append(" : ")
                .AppendLine(GetReadOnlyBaseInterfaceName(type));
            builder.Append(indent).AppendLine("{");

            foreach (var member in members)
            {
                builder.Append(indent)
                    .Append("    ")
                    .Append(member.TypeName)
                    .Append(' ')
                    .Append(member.Name)
                    .AppendLine(" { get; }");
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent)
                .Append(accessibility)
                .Append(" partial class ")
                .Append(type.Name)
                .Append(" : ")
                .AppendLine(interfaceName);
            builder.Append(indent).AppendLine("{");

            foreach (var member in members)
            {
                builder.Append(indent)
                    .Append("    ")
                    .Append(member.TypeName)
                    .Append(' ')
                    .Append(interfaceName)
                    .Append('.')
                    .Append(member.Name)
                    .Append(" => ")
                    .Append(member.Name)
                    .AppendLine(";");
            }

            builder.Append(indent).AppendLine("}");

            if (hasNamespace)
            {
                builder.AppendLine("}");
            }
        }

        private static string GetReadOnlyBaseInterfaceName(SourceType type)
        {
            return type.TryGetEntityCollectionModelArguments(out var entityIdType, out var dataType)
                ? "global::MyArchitecture.Core.IReadOnlyEntityCollectionModel<" + entityIdType + ", " + dataType + ">"
                : "global::MyArchitecture.Core.IReadOnlyModel";
        }

        private static string BuildRegistrationSource(
            string className,
            IEnumerable<SourceType> types,
            Func<string, bool> pathFilter)
        {
            var registrations = new List<Registration>();

            foreach (var type in types
                         .Where(type => type.IsRuntimeConcreteType)
                         .Where(type => pathFilter(type.Path)))
            {
                if (type.IsModel)
                {
                    registrations.Add(new Registration("RegisterModel", type));
                }

                if (type.HasBaseOrInterface("GameService"))
                {
                    registrations.Add(new Registration("RegisterGameService", type));
                }

                if (type.HasBaseOrInterface("Presenter"))
                {
                    registrations.Add(new Registration("RegisterPresenter", type));
                }

                if (type.IsCommand)
                {
                    registrations.Add(new Registration("RegisterCommand", type));
                }

                if (type.IsQuery)
                {
                    registrations.Add(new Registration("RegisterQuery", type));
                }

                if (type.HasBaseOrInterface("IUtility"))
                {
                    registrations.Add(new Registration("RegisterUtility", type));
                }

                if (type.HasBaseOrInterface("IEvent"))
                {
                    registrations.Add(new Registration("RegisterEvent", type));
                }
            }

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// This file is generated by ArchitectureGeneratedSourceRecovery.");
            builder.AppendLine();
            builder.AppendLine("namespace MyArchitecture.Integration");
            builder.AppendLine("{");
            builder.Append("    internal static class ").AppendLine(className);
            builder.AppendLine("    {");
            builder.AppendLine("        public static void Register(ArchitectureRegistrationContext context)");
            builder.AppendLine("        {");

            foreach (var registration in registrations
                         .Distinct()
                         .OrderBy(registration => registration.MethodOrder)
                         .ThenBy(registration => registration.Type.FullName))
            {
                builder.Append("            context.")
                    .Append(registration.MethodName)
                    .Append('<')
                    .Append(registration.Type.GlobalFullName)
                    .AppendLine(">();");
            }

            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static bool IsFrameworkOwnedPath(string path)
        {
            return !string.IsNullOrEmpty(path) &&
                   path.Replace('\\', '/').StartsWith(FrameworkRootPath, StringComparison.Ordinal);
        }

        private static bool WriteIfChanged(string outputPath, string source)
        {
            var directory = Path.GetDirectoryName(outputPath);

            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            if (File.Exists(outputPath) && File.ReadAllText(outputPath) == source)
            {
                return false;
            }

            File.WriteAllText(outputPath, source, Encoding.UTF8);
            AssetDatabase.ImportAsset(outputPath);
            return true;
        }

        private readonly struct Registration : IEquatable<Registration>
        {
            public Registration(string methodName, SourceType type)
            {
                MethodName = methodName;
                Type = type;
            }

            public string MethodName { get; }
            public SourceType Type { get; }

            public int MethodOrder
            {
                get
                {
                    switch (MethodName)
                    {
                        case "RegisterModel": return 0;
                        case "RegisterGameService": return 1;
                        case "RegisterPresenter": return 2;
                        case "RegisterCommand": return 3;
                        case "RegisterQuery": return 4;
                        case "RegisterUtility": return 5;
                        case "RegisterEvent": return 6;
                        default: return int.MaxValue;
                    }
                }
            }

            public bool Equals(Registration other)
            {
                return MethodName == other.MethodName && Type.FullName == other.Type.FullName;
            }

            public override bool Equals(object obj)
            {
                return obj is Registration other && Equals(other);
            }

            public override int GetHashCode()
            {
                unchecked
                {
                    return ((MethodName != null ? MethodName.GetHashCode() : 0) * 397) ^
                           (Type.FullName != null ? Type.FullName.GetHashCode() : 0);
                }
            }
        }
    }

    internal sealed class ArchitectureGeneratedSourceRecoveryPostprocessor : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (ContainsRuntimeScriptChange(importedAssets) ||
                ContainsRuntimeScriptChange(deletedAssets) ||
                ContainsRuntimeScriptChange(movedAssets) ||
                ContainsRuntimeScriptChange(movedFromAssetPaths))
            {
                EditorApplication.delayCall += ArchitectureGeneratedSourceRecovery.Generate;
            }
        }

        private static bool ContainsRuntimeScriptChange(IEnumerable<string> paths)
        {
            return paths != null && paths.Any(SourceScanner.IsRuntimeSourcePath);
        }
    }

    internal static class SourceScanner
    {
        private static readonly Regex TypeRegex = new Regex(
            @"(?:(?<access>public|internal)\s+)?(?<modifiers>(?:(?:sealed|abstract|partial|static|readonly|unsafe|new)\s+)*)(?<kind>class|struct)\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)(?:\s*:\s*(?<bases>[^{};]+?))?\s*\{",
            RegexOptions.Singleline | RegexOptions.Compiled);
        private static readonly Regex NamespaceRegex = new Regex(
            @"\bnamespace\s+(?<namespace>[A-Za-z_][A-Za-z0-9_.]*)\s*\{",
            RegexOptions.Compiled);
        private static readonly Regex FileScopedNamespaceRegex = new Regex(
            @"^\s*namespace\s+(?<namespace>[A-Za-z_][A-Za-z0-9_.]*)\s*;",
            RegexOptions.Multiline | RegexOptions.Compiled);
        private static readonly Regex UsingRegex = new Regex(
            @"^\s*using\s+(?!static\b)[^;]+;",
            RegexOptions.Multiline | RegexOptions.Compiled);

        public static IReadOnlyList<SourceType> Scan()
        {
            if (!Directory.Exists("Assets"))
            {
                return Array.Empty<SourceType>();
            }

            var result = new List<SourceType>();

            foreach (var root in new[]
                {
                    "Assets",
                    "Packages/com.seikasan.myarchitecture"
                })
            {
                if (!Directory.Exists(root))
                {
                    continue;
                }

                foreach (var path in Directory.GetFiles(root, "*.cs", SearchOption.AllDirectories))
                {
                    var normalizedPath = NormalizePath(path);

                    if (!IsRuntimeSourcePath(normalizedPath))
                    {
                        continue;
                    }

                    var source = RemoveComments(File.ReadAllText(normalizedPath));
                    var fileScopedNamespace = GetFileScopedNamespace(source);
                    var usingDirectives = GetUsingDirectives(source);
                    var typeRanges = new List<SourceRange>();

                    foreach (Match match in TypeRegex.Matches(source))
                    {
                        if (typeRanges.Any(range => range.Contains(match.Index)))
                        {
                            continue;
                        }

                        var openBrace = source.IndexOf('{', match.Index + match.Length - 1);
                        var closeBrace = openBrace >= 0 ? FindMatchingBrace(source, openBrace) : -1;

                        if (closeBrace < 0)
                        {
                            continue;
                        }

                        typeRanges.Add(new SourceRange(openBrace, closeBrace));

                        result.Add(new SourceType(
                            normalizedPath,
                            GetNamespaceAt(source, match.Index, fileScopedNamespace),
                            match.Groups["access"].Value,
                            match.Groups["modifiers"].Value,
                            match.Groups["kind"].Value,
                            match.Groups["name"].Value,
                            NormalizeWhitespace(match.Groups["bases"].Value),
                            source.Substring(openBrace + 1, closeBrace - openBrace - 1),
                            usingDirectives));
                    }
                }
            }

            return result;
        }

        public static bool IsRuntimeSourcePath(string path)
        {
            if (string.IsNullOrEmpty(path))
            {
                return false;
            }

            var normalized = NormalizePath(path);

            return normalized.EndsWith(".cs", StringComparison.OrdinalIgnoreCase) &&
               (normalized.StartsWith("Assets/", StringComparison.Ordinal) ||
                normalized.StartsWith("Packages/com.seikasan.myarchitecture/", StringComparison.Ordinal)) &&
               !ContainsIgnoredFolder(normalized) &&
               !normalized.Contains("/Editor/") &&
               !normalized.Contains("/Generated/") &&
               !normalized.Contains("/Tests/");
        }

        private static bool ContainsIgnoredFolder(string path)
        {
            var parts = path.Split('/');

            foreach (var part in parts)
            {
                if (part.EndsWith("~", StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        public static IReadOnlyList<string> SplitTopLevelCommaSeparated(string text)
        {
            var result = new List<string>();

            if (string.IsNullOrWhiteSpace(text))
            {
                return result;
            }

            var depth = 0;
            var start = 0;

            for (var i = 0; i < text.Length; i++)
            {
                if (text[i] == '<') depth++;
                if (text[i] == '>') depth = Math.Max(0, depth - 1);
                if (text[i] != ',' || depth != 0) continue;

                AddPart(text, start, i, result);
                start = i + 1;
            }

            AddPart(text, start, text.Length, result);
            return result;
        }

        public static string NormalizeWhitespace(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? string.Empty : Regex.Replace(value.Trim(), @"\s+", " ");
        }

        private static IReadOnlyList<string> GetUsingDirectives(string source)
        {
            return UsingRegex.Matches(source)
                .Select(match => NormalizeWhitespace(match.Value))
                .Distinct()
                .OrderBy(value => value)
                .ToArray();
        }

        private static string GetFileScopedNamespace(string source)
        {
            var match = FileScopedNamespaceRegex.Match(source);
            return match.Success ? match.Groups["namespace"].Value : string.Empty;
        }

        private static string GetNamespaceAt(string source, int index, string fileScopedNamespace)
        {
            if (!string.IsNullOrEmpty(fileScopedNamespace))
            {
                return fileScopedNamespace;
            }

            foreach (Match match in NamespaceRegex.Matches(source))
            {
                var openBrace = source.IndexOf('{', match.Index + match.Length - 1);
                var closeBrace = openBrace >= 0 ? FindMatchingBrace(source, openBrace) : -1;

                if (openBrace >= 0 && index > openBrace && closeBrace > index)
                {
                    return match.Groups["namespace"].Value;
                }
            }

            return string.Empty;
        }

        private static string RemoveComments(string source)
        {
            return Regex.Replace(source, @"/\*.*?\*/|//.*?$", string.Empty, RegexOptions.Singleline | RegexOptions.Multiline);
        }

        private static int FindMatchingBrace(string source, int openBrace)
        {
            var depth = 0;

            for (var i = openBrace; i < source.Length; i++)
            {
                if (source[i] == '{') depth++;
                if (source[i] != '}') continue;

                depth--;

                if (depth == 0)
                {
                    return i;
                }
            }

            return -1;
        }

        private static void AddPart(string text, int start, int end, ICollection<string> result)
        {
            var value = text.Substring(start, end - start).Trim();
            if (!string.IsNullOrEmpty(value)) result.Add(value);
        }

        private static string NormalizePath(string path)
        {
            return path.Replace('\\', '/');
        }

        private readonly struct SourceRange
        {
            public SourceRange(int start, int end)
            {
                Start = start;
                End = end;
            }

            private int Start { get; }
            private int End { get; }
            public bool Contains(int index) => index > Start && index < End;
        }
    }

    internal sealed class SourceType
    {
        private static readonly Regex PropertyRegex = new Regex(
            @"\bpublic\s+(?!static\b)(?:(?:new|virtual|override|sealed)\s+)*(?<type>[^{};=]+?)\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?:\{\s*get\b|=>)",
            RegexOptions.Singleline | RegexOptions.Compiled);
        private static readonly Regex ReadOnlyFieldRegex = new Regex(
            @"\bpublic\s+readonly\s+(?!static\b)(?<type>[^;=]+?)\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?:=|;)",
            RegexOptions.Singleline | RegexOptions.Compiled);

        private static readonly string[] CommandNames =
        {
            "Command", "AsyncCommand", "TryCommand", "AsyncTryCommand",
            "ResultCommand", "AsyncResultCommand", "ICommand", "IAsyncCommand",
            "ITryCommand", "IAsyncTryCommand", "IResultCommand", "IAsyncResultCommand"
        };

        private static readonly string[] QueryNames =
        {
            "Query", "AsyncQuery", "IQuery", "IAsyncQuery"
        };

        public SourceType(
            string path,
            string @namespace,
            string access,
            string modifiers,
            string kind,
            string name,
            string baseList,
            string body,
            IReadOnlyList<string> usingDirectives)
        {
            Path = path;
            Namespace = @namespace;
            Access = access;
            Modifiers = modifiers;
            Kind = kind;
            Name = name;
            BaseList = baseList;
            Body = body;
            UsingDirectives = usingDirectives;
        }

        public string Path { get; }
        public string Namespace { get; }
        public string Access { get; }
        public string Modifiers { get; }
        public string Kind { get; }
        public string Name { get; }
        public string BaseList { get; }
        public string Body { get; }
        public IReadOnlyList<string> UsingDirectives { get; }
        public string FullName => string.IsNullOrEmpty(Namespace) ? Name : Namespace + "." + Name;
        public string GlobalFullName => "global::" + FullName;
        public bool IsPublic => Access == "public";
        public bool IsConcreteClass => Kind == "class" && !HasModifier("abstract") && !HasModifier("static");
        public bool IsRuntimeConcreteType => (IsConcreteClass || Kind == "struct") && !string.IsNullOrEmpty(Name);
        public bool IsModel => HasBaseOrInterface("Model") || HasBaseOrInterface("EntityCollectionModel");
        public bool IsPartialModel => IsConcreteClass && HasModifier("partial") && IsModel;
        public bool IsCommand => HasAnyBaseOrInterface(CommandNames);
        public bool IsQuery => HasAnyBaseOrInterface(QueryNames);

        public bool HasBaseOrInterface(string baseName)
        {
            return GetBaseOrInterfaceNames().Any(name => name == baseName);
        }

        public bool TryGetEntityCollectionModelArguments(out string entityIdType, out string dataType)
        {
            foreach (var baseType in SourceScanner.SplitTopLevelCommaSeparated(BaseList))
            {
                var value = SourceScanner.NormalizeWhitespace(baseType);
                var genericStart = value.IndexOf('<');
                var genericEnd = value.LastIndexOf('>');

                if (genericStart < 0 || genericEnd <= genericStart ||
                    GetSimpleTypeName(value.Substring(0, genericStart)) != "EntityCollectionModel")
                {
                    continue;
                }

                var arguments = SourceScanner.SplitTopLevelCommaSeparated(
                    value.Substring(genericStart + 1, genericEnd - genericStart - 1));

                if (arguments.Count == 2)
                {
                    entityIdType = arguments[0];
                    dataType = arguments[1];
                    return true;
                }
            }

            entityIdType = string.Empty;
            dataType = string.Empty;
            return false;
        }

        public IReadOnlyList<ReadOnlyMember> GetReadOnlyMembers()
        {
            var members = new List<ReadOnlyMember>();

            foreach (Match match in PropertyRegex.Matches(Body))
            {
                var name = match.Groups["name"].Value;
                if (name == "this") continue;
                members.Add(new ReadOnlyMember(name, NormalizeTypeName(match.Groups["type"].Value)));
            }

            foreach (Match match in ReadOnlyFieldRegex.Matches(Body))
            {
                members.Add(new ReadOnlyMember(
                    match.Groups["name"].Value,
                    GetReadOnlyFieldTypeName(match.Groups["type"].Value)));
            }

            return members.GroupBy(member => member.Name).Select(group => group.First()).ToArray();
        }

        private bool HasAnyBaseOrInterface(IEnumerable<string> names)
        {
            var set = new HashSet<string>(names);
            return GetBaseOrInterfaceNames().Any(set.Contains);
        }

        private IEnumerable<string> GetBaseOrInterfaceNames()
        {
            return SourceScanner.SplitTopLevelCommaSeparated(BaseList)
                .Select(GetSimpleTypeName)
                .Where(name => !string.IsNullOrEmpty(name));
        }

        private bool HasModifier(string modifier)
        {
            return Modifiers.Split(new[] { ' ', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .Any(value => value == modifier);
        }

        private static string GetReadOnlyFieldTypeName(string fieldType)
        {
            var typeName = NormalizeTypeName(fieldType);
            return TryGetReactivePropertyValueType(typeName, out var valueType)
                ? "global::R3.ReadOnlyReactiveProperty<" + valueType + ">"
                : typeName;
        }

        private static bool TryGetReactivePropertyValueType(string typeName, out string valueType)
        {
            var genericStart = typeName.IndexOf('<');
            var genericEnd = typeName.LastIndexOf('>');

            if (genericStart < 0 || genericEnd <= genericStart ||
                GetSimpleTypeName(typeName.Substring(0, genericStart)) != "ReactiveProperty")
            {
                valueType = string.Empty;
                return false;
            }

            valueType = typeName.Substring(genericStart + 1, genericEnd - genericStart - 1);
            return true;
        }

        private static string GetSimpleTypeName(string typeName)
        {
            var value = SourceScanner.NormalizeWhitespace(typeName).Replace("global::", string.Empty);
            var genericStart = value.IndexOf('<');
            if (genericStart >= 0) value = value.Substring(0, genericStart);
            var namespaceStart = value.LastIndexOf('.');
            return namespaceStart >= 0 ? value.Substring(namespaceStart + 1) : value;
        }

        private static string NormalizeTypeName(string typeName)
        {
            return SourceScanner.NormalizeWhitespace(typeName);
        }
    }

    internal readonly struct ReadOnlyMember
    {
        public ReadOnlyMember(string name, string typeName)
        {
            Name = name;
            TypeName = typeName;
        }

        public string Name { get; }
        public string TypeName { get; }
    }
}
