using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using MyArchitecture.Core;
using UnityEditor;
using UnityEngine;

namespace MyArchitecture.Editor
{
    internal static class ReadOnlyModelGenerator
    {
        private const string ReactivePropertyFullName = "R3.ReactiveProperty`1";

        private const string ApplicationOutputPath =
            "Assets/Generated/MyArchitecture/ReadOnlyModels.g.cs";

        private const string PackageOutputPath =
            "Packages/com.seikasan.myarchitecture/Runtime/Generated/Package/ReadOnlyPackageModels.g.cs";

        private const string FrameworkRootPath =
            "Packages/com.seikasan.myarchitecture/";

        public static bool Generate()
        {
            bool applicationChanged = Generate(
                ApplicationOutputPath,
                path => !IsFrameworkOwnedPath(path));
            bool packageChanged = Generate(
                PackageOutputPath,
                IsFrameworkOwnedPath);

            return applicationChanged || packageChanged;
        }

        private static bool Generate(
            string outputPath,
            Func<string, bool> scriptPathFilter)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// This file is generated by ReadOnlyModelGenerator.");

            var modelTypes = TypeCache.GetTypesDerivedFrom<Model>()
                .Where(IsGeneratableModel)
                .OrderBy(type => type.FullName)
                .ToArray();

            foreach (var modelType in modelTypes)
            {
                var scriptPath = FindScriptPath(modelType);

                if (string.IsNullOrEmpty(scriptPath))
                {
                    Debug.LogWarning(
                        $"ReadOnlyModelGenerator skipped {modelType.FullName}: source script was not found.");
                    continue;
                }

                if (!scriptPathFilter(scriptPath))
                {
                    continue;
                }

                if (!IsPartialModel(modelType, scriptPath))
                {
                    Debug.LogError(
                        $"ReadOnlyModelGenerator skipped {modelType.FullName}: model class must be partial.");
                    continue;
                }

                builder.AppendLine();
                AppendModel(builder, modelType);
            }

            return WriteIfChanged(outputPath, builder.ToString());
        }

        private static bool IsGeneratableModel(Type type)
        {
            return type.IsClass &&
                   !type.IsAbstract &&
                   !type.IsNested &&
                   !type.IsGenericTypeDefinition &&
                   !type.ContainsGenericParameters;
        }

        private static string FindScriptPath(Type type)
        {
            var guids = AssetDatabase.FindAssets($"{type.Name} t:Script");

            foreach (string guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);

                if (script != null && script.GetClass() == type)
                {
                    return path;
                }
            }

            return null;
        }

        private static bool IsPartialModel(Type type, string scriptPath)
        {
            var source = File.ReadAllText(scriptPath);
            var pattern = $@"\bpartial\s+class\s+{Regex.Escape(type.Name)}\b";
            return Regex.IsMatch(source, pattern);
        }

        private static void AppendModel(StringBuilder builder, Type modelType)
        {
            var indent = string.Empty;

            if (!string.IsNullOrEmpty(modelType.Namespace))
            {
                builder.Append("namespace ")
                    .AppendLine(modelType.Namespace);
                builder.AppendLine("{");
                indent = "    ";
            }

            var accessibility = modelType.IsPublic ? "public" : "internal";
            var interfaceName = $"IReadOnly{modelType.Name}";
            var baseInterfaceName = GetReadOnlyBaseInterfaceName(modelType);
            var members = modelType
                .GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(IsReadableProperty)
                .Where(property => !IsFrameworkBaseMember(property))
                .Select(property => new ReadOnlyMember(
                    property.Name,
                    GetTypeName(property.PropertyType)))
                .Concat(modelType
                    .GetFields(BindingFlags.Instance | BindingFlags.Public)
                    .Where(IsReadableField)
                    .Where(field => !IsFrameworkBaseMember(field))
                    .Select(field => new ReadOnlyMember(
                        field.Name,
                        GetReadOnlyFieldTypeName(field.FieldType))))
                .OrderBy(member => member.Name)
                .ToArray();

            builder.Append(indent)
                .Append(accessibility)
                .Append(" interface ")
                .Append(interfaceName)
                .Append(" : ")
                .AppendLine(baseInterfaceName);
            builder.Append(indent).AppendLine("{");

            foreach (var member in members)
            {
                builder.Append(indent)
                    .Append("    ")
                    .Append(member.TypeName)
                    .Append(' ')
                    .Append(member.Name)
                    .AppendLine(" { get; }");
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            builder.Append(indent)
                .Append(accessibility)
                .Append(" partial class ")
                .Append(modelType.Name)
                .Append(" : ")
                .AppendLine(interfaceName);
            builder.Append(indent).AppendLine("{");

            foreach (var member in members)
            {
                builder.Append(indent)
                    .Append("    ")
                    .Append(member.TypeName)
                    .Append(' ')
                    .Append(interfaceName)
                    .Append('.')
                    .Append(member.Name)
                    .Append(" => ")
                    .Append(member.Name)
                    .AppendLine(";");
            }

            builder.Append(indent).AppendLine("}");

            if (!string.IsNullOrEmpty(modelType.Namespace))
            {
                builder.AppendLine("}");
            }
        }

        private static bool IsReadableProperty(PropertyInfo property)
        {
            var getter = property.GetMethod;

            return getter != null &&
                   getter.IsPublic &&
                   !getter.IsStatic &&
                   property.GetIndexParameters().Length == 0;
        }

        private static bool IsReadableField(FieldInfo field)
        {
            return field.IsPublic &&
                   field.IsInitOnly &&
                   !field.IsStatic &&
                   !field.IsLiteral;
        }

        private static string GetReadOnlyBaseInterfaceName(Type modelType)
        {
            if (TryGetEntityCollectionModelArguments(
                    modelType,
                    out var entityIdType,
                    out var dataType))
            {
                return
                    "global::MyArchitecture.Core.IReadOnlyEntityCollectionModel<" +
                    GetTypeName(entityIdType) +
                    ", " +
                    GetTypeName(dataType) +
                    ">";
            }

            return "global::MyArchitecture.Core.IReadOnlyModel";
        }

        private static bool IsFrameworkBaseMember(MemberInfo member)
        {
            if (member.DeclaringType == null)
            {
                return false;
            }

            return member.DeclaringType == typeof(ArchitectureObject) ||
                   member.DeclaringType == typeof(Model) ||
                   IsEntityCollectionModelType(member.DeclaringType);
        }

        private static bool TryGetEntityCollectionModelArguments(
            Type modelType,
            out Type entityIdType,
            out Type dataType)
        {
            for (var current = modelType; current != null; current = current.BaseType)
            {
                if (!IsEntityCollectionModelType(current))
                {
                    continue;
                }

                var arguments = current.GetGenericArguments();
                entityIdType = arguments[0];
                dataType = arguments[1];
                return true;
            }

            entityIdType = null;
            dataType = null;
            return false;
        }

        private static bool IsEntityCollectionModelType(Type type)
        {
            return type.IsGenericType &&
                   type.GetGenericTypeDefinition() == typeof(EntityCollectionModel<,>);
        }

        private static string GetReadOnlyFieldTypeName(Type fieldType)
        {
            if (TryGetReactivePropertyValueType(fieldType, out var valueType))
            {
                return $"global::R3.ReadOnlyReactiveProperty<{GetTypeName(valueType)}>";
            }

            return GetTypeName(fieldType);
        }

        private static bool TryGetReactivePropertyValueType(Type type, out Type valueType)
        {
            for (var current = type; current != null; current = current.BaseType)
            {
                if (current.IsGenericType &&
                    current.GetGenericTypeDefinition().FullName == ReactivePropertyFullName)
                {
                    valueType = current.GetGenericArguments()[0];
                    return true;
                }
            }

            valueType = null;
            return false;
        }

        private static string GetTypeName(Type type)
        {
            if (type.IsGenericParameter)
            {
                return type.Name;
            }

            if (type.IsArray)
            {
                return $"{GetTypeName(type.GetElementType())}[]";
            }

            if (type.IsGenericType)
            {
                var genericType = type.GetGenericTypeDefinition();
                var genericName = GetNonGenericTypeName(genericType);
                var tickIndex = genericName.IndexOf('`');

                if (tickIndex >= 0)
                {
                    genericName = genericName.Substring(0, tickIndex);
                }

                var arguments = string.Join(
                    ", ",
                    type.GetGenericArguments().Select(GetTypeName));

                return $"{genericName}<{arguments}>";
            }

            return GetNonGenericTypeName(type);
        }

        private static string GetNonGenericTypeName(Type type)
        {
            var fullName = type.FullName ?? type.Name;
            return "global::" + fullName.Replace('+', '.');
        }

        private static bool IsFrameworkOwnedPath(string path)
        {
            if (string.IsNullOrEmpty(path))
            {
                return false;
            }

            var normalized = path.Replace('\\', '/');

            return normalized.StartsWith(
                FrameworkRootPath,
                StringComparison.Ordinal);
        }

        private readonly struct ReadOnlyMember
        {
            public ReadOnlyMember(string name, string typeName)
            {
                Name = name;
                TypeName = typeName;
            }

            public string Name { get; }

            public string TypeName { get; }
        }

        private static bool WriteIfChanged(
            string outputPath,
            string source)
        {
            var directory = Path.GetDirectoryName(outputPath);

            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            if (File.Exists(outputPath) &&
                File.ReadAllText(outputPath) == source)
            {
                return false;
            }

            File.WriteAllText(outputPath, source, Encoding.UTF8);
            AssetDatabase.ImportAsset(outputPath);

            return true;
        }
    }
}
